language: node_js
sudo: false # Use container boxes for tests
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
script: gulp travis
matrix:
  fast_finish: true